apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playwright-states-pvc
  namespace: resell-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-pvc
  namespace: resell-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
