apiVersion: v1
kind: Secret
metadata:
  name: resell-secret
  namespace: resell-assistant
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:cfghhm7f@resell-manager-postgresql.ns-3zn44u6p.svc:5432/postgres"
  REDIS_URL: "redis://default:Xv01aH061L@resell--manager-redis-redis.ns-3zn44u6p.svc:6379/0"
  CELERY_BROKER_URL: "redis://default:Xv01aH061L@resell--manager-redis-redis.ns-3zn44u6p.svc:6379/1"
  CELERY_RESULT_BACKEND: "redis://default:Xv01aH061L@resell--manager-redis-redis.ns-3zn44u6p.svc:6379/2"
  SECRET_KEY: "CHANGE-ME-TO-RANDOM-STRING-IN-PRODUCTION"
  LLM_API_KEY: ""
  DINGTALK_WEBHOOK_URL: "https://oapi.dingtalk.com/robot/send?access_token=db4f47b563c55d361189e74de38717b6e48b3edcbd0a0e6f0df8be306d42111e"
  DINGTALK_SECRET: "SEC9ff09c7fd652e3cd8a407bf55b06c8e727c161f8d5458b0a8c06fa752fc44280"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
