"""initial_schema

Revision ID: 4a0674d8a46c
Revises: 
Create Date: 2026-04-09 11:19:29.479629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0674d8a46c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('identity_group', sa.String(length=64), nullable=False),
    sa.Column('niche', sa.String(length=128), nullable=True),
    sa.Column('proxy_url', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('viewport', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('cookie_state_path', sa.Text(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('daily_publish_limit', sa.Integer(), nullable=False),
    sa.Column('daily_published_count', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_platform'), 'accounts', ['platform'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('suggestion_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('auto_executable', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_suggestion_type'), 'ai_suggestions', ['suggestion_type'], unique=False)
    op.create_table('daily_checks',
    sa.Column('check_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_checks_check_date'), 'daily_checks', ['check_date'], unique=False)
    op.create_table('daily_reports',
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=True)
    op.create_table('notifications',
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('source_platform', sa.Enum('PINDUODUO', 'TAOBAO', 'XIANYU', 'XIAOHONGSHU', 'DOUYIN', name='platform'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('product_type', sa.Enum('PHYSICAL', 'VIRTUAL', name='producttype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('shipping_fee', sa.Float(), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('sku_info', sa.JSON(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_active', 'products', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_source_id'), 'products', ['source_id'], unique=False)
    op.create_index(op.f('ix_products_source_platform'), 'products', ['source_platform'], unique=False)
    op.create_index('ix_products_source_platform_source_id', 'products', ['source_platform', 'source_id'], unique=True)
    op.create_table('reply_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_templates_category'), 'reply_templates', ['category'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('tasks',
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('xhs_competitor_notes',
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('xhs_note_id', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('cover_style', sa.String(length=64), nullable=True),
    sa.Column('content_structure', sa.String(length=64), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('collects', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('interaction_rate', sa.Float(), nullable=True),
    sa.Column('has_product_link', sa.Boolean(), nullable=False),
    sa.Column('purchase_intent_ratio', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xhs_note_id')
    )
    op.create_index(op.f('ix_xhs_competitor_notes_keyword'), 'xhs_competitor_notes', ['keyword'], unique=False)
    op.create_table('xhs_content_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xhs_hot_topics',
    sa.Column('topic_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('note_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate_daily', sa.Float(), nullable=True),
    sa.Column('growth_rate_weekly', sa.Float(), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_hot_topics_topic_name'), 'xhs_hot_topics', ['topic_name'], unique=False)
    op.create_index('ix_xhs_hot_topics_trending', 'xhs_hot_topics', ['is_trending', 'captured_at'], unique=False)
    op.create_table('xhs_trending_keywords',
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('search_volume_estimated', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('related_products_found', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xhs_trending_keywords_keyword'), 'xhs_trending_keywords', ['keyword'], unique=False)
    op.create_table('orders',
    sa.Column('sale_platform', sa.String(length=32), nullable=False),
    sa.Column('sale_order_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('buyer_name', sa.String(length=128), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('buyer_phone', sa.String(length=32), nullable=True),
    sa.Column('buyer_note', sa.Text(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('actual_profit', sa.Float(), nullable=True),
    sa.Column('sku_info', sa.JSON(), nullable=True),
    sa.Column('source_sku_mapping', sa.JSON(), nullable=True),
    sa.Column('source_platform', sa.String(length=32), nullable=True),
    sa.Column('source_order_id', sa.String(length=128), nullable=True),
    sa.Column('source_order_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_order_id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_sale_platform'), 'orders', ['sale_platform'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_platform', 'orders', ['status', 'sale_platform'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_product_id'), 'price_snapshots', ['product_id'], unique=False)
    op.create_index('ix_price_snapshots_product_time', 'price_snapshots', ['product_id', 'captured_at'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('SOURCE_MAIN', 'SOURCE_DETAIL', 'SOURCE_REVIEW', 'USER_UPLOAD', 'PROCESSED', name='imagesource'), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('clip_vector', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_matches',
    sa.Column('source_product_id', sa.UUID(), nullable=False),
    sa.Column('target_product_id', sa.UUID(), nullable=False),
    sa.Column('target_platform', sa.Enum('PINDUODUO', 'TAOBAO', 'XIANYU', 'XIAOHONGSHU', 'DOUYIN', name='platform'), nullable=False),
    sa.Column('text_similarity', sa.Float(), nullable=True),
    sa.Column('phash_similarity', sa.Float(), nullable=True),
    sa.Column('clip_similarity', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_matches_source_target', 'product_matches', ['source_product_id', 'target_product_id'], unique=True)
    op.create_table('product_scores',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_scores_product_id'), 'product_scores', ['product_id'], unique=False)
    op.create_index('ix_product_scores_type_score', 'product_scores', ['score_type', 'total_score'], unique=False)
    op.create_table('virtual_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('delivery_content', sa.Text(), nullable=False),
    sa.Column('delivery_message', sa.Text(), nullable=False),
    sa.Column('backup_links', sa.JSON(), nullable=True),
    sa.Column('total_sold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_products_product_id'), 'virtual_products', ['product_id'], unique=True)
    op.create_table('xhs_notes',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('xhs_note_id', sa.String(length=64), nullable=True),
    sa.Column('note_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('linked_product_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_monetized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xhs_note_id')
    )
    op.create_index(op.f('ix_xhs_notes_account_id'), 'xhs_notes', ['account_id'], unique=False)
    op.create_index('ix_xhs_notes_account_status', 'xhs_notes', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_xhs_notes_product_id'), 'xhs_notes', ['product_id'], unique=False)
    op.create_index(op.f('ix_xhs_notes_status'), 'xhs_notes', ['status'], unique=False)
    op.create_table('xhs_shop_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('xhs_product_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xhs_product_id')
    )
    op.create_index(op.f('ix_xhs_shop_products_account_id'), 'xhs_shop_products', ['account_id'], unique=False)
    op.create_index(op.f('ix_xhs_shop_products_product_id'), 'xhs_shop_products', ['product_id'], unique=False)
    op.create_table('xianyu_listings',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('xianyu_item_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_cost', sa.Float(), nullable=False),
    sa.Column('expected_profit', sa.Float(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('sku_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('wants', sa.Integer(), nullable=False),
    sa.Column('chats', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xianyu_item_id')
    )
    op.create_index(op.f('ix_xianyu_listings_account_id'), 'xianyu_listings', ['account_id'], unique=False)
    op.create_index('ix_xianyu_listings_account_status', 'xianyu_listings', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_xianyu_listings_product_id'), 'xianyu_listings', ['product_id'], unique=False)
    op.create_index(op.f('ix_xianyu_listings_status'), 'xianyu_listings', ['status'], unique=False)
    op.create_table('xianyu_market_data',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('active_listings', sa.Integer(), nullable=False),
    sa.Column('total_wants', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('price_avg', sa.Float(), nullable=True),
    sa.Column('price_cv', sa.Float(), nullable=True),
    sa.Column('top5_sales', sa.JSON(), nullable=True),
    sa.Column('seller_distribution', sa.JSON(), nullable=True),
    sa.Column('new_listings_7d', sa.Integer(), nullable=True),
    sa.Column('total_listings_7d', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xianyu_market_data_keyword'), 'xianyu_market_data', ['keyword'], unique=False)
    op.create_index(op.f('ix_xianyu_market_data_product_id'), 'xianyu_market_data', ['product_id'], unique=False)
    op.create_index('ix_xianyu_market_product_time', 'xianyu_market_data', ['product_id', 'captured_at'], unique=False)
    op.create_table('conversations',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_name', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversations_platform'), 'conversations', ['platform'], unique=False)
    op.create_table('logistics',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('tracking_events', sa.JSON(), nullable=True),
    sa.Column('synced_to_sale_platform', sa.Boolean(), nullable=False),
    sa.Column('last_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_order_id'), 'logistics', ['order_id'], unique=False)
    op.create_index(op.f('ix_logistics_tracking_number'), 'logistics', ['tracking_number'], unique=False)
    op.create_table('virtual_deliveries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('virtual_product_id', sa.UUID(), nullable=False),
    sa.Column('delivered_content', sa.Text(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['virtual_product_id'], ['virtual_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_deliveries_order_id'), 'virtual_deliveries', ['order_id'], unique=False)
    op.create_table('xhs_note_analytics',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('collects', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('views_estimated', sa.Integer(), nullable=True),
    sa.Column('interaction_rate', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['xhs_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_xhs_analytics_note_time', 'xhs_note_analytics', ['note_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_xhs_note_analytics_note_id'), 'xhs_note_analytics', ['note_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_approved', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_xhs_note_analytics_note_id'), table_name='xhs_note_analytics')
    op.drop_index('ix_xhs_analytics_note_time', table_name='xhs_note_analytics')
    op.drop_table('xhs_note_analytics')
    op.drop_index(op.f('ix_virtual_deliveries_order_id'), table_name='virtual_deliveries')
    op.drop_table('virtual_deliveries')
    op.drop_index(op.f('ix_logistics_tracking_number'), table_name='logistics')
    op.drop_index(op.f('ix_logistics_order_id'), table_name='logistics')
    op.drop_table('logistics')
    op.drop_index(op.f('ix_conversations_platform'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_xianyu_market_product_time', table_name='xianyu_market_data')
    op.drop_index(op.f('ix_xianyu_market_data_product_id'), table_name='xianyu_market_data')
    op.drop_index(op.f('ix_xianyu_market_data_keyword'), table_name='xianyu_market_data')
    op.drop_table('xianyu_market_data')
    op.drop_index(op.f('ix_xianyu_listings_status'), table_name='xianyu_listings')
    op.drop_index(op.f('ix_xianyu_listings_product_id'), table_name='xianyu_listings')
    op.drop_index('ix_xianyu_listings_account_status', table_name='xianyu_listings')
    op.drop_index(op.f('ix_xianyu_listings_account_id'), table_name='xianyu_listings')
    op.drop_table('xianyu_listings')
    op.drop_index(op.f('ix_xhs_shop_products_product_id'), table_name='xhs_shop_products')
    op.drop_index(op.f('ix_xhs_shop_products_account_id'), table_name='xhs_shop_products')
    op.drop_table('xhs_shop_products')
    op.drop_index(op.f('ix_xhs_notes_status'), table_name='xhs_notes')
    op.drop_index(op.f('ix_xhs_notes_product_id'), table_name='xhs_notes')
    op.drop_index('ix_xhs_notes_account_status', table_name='xhs_notes')
    op.drop_index(op.f('ix_xhs_notes_account_id'), table_name='xhs_notes')
    op.drop_table('xhs_notes')
    op.drop_index(op.f('ix_virtual_products_product_id'), table_name='virtual_products')
    op.drop_table('virtual_products')
    op.drop_index('ix_product_scores_type_score', table_name='product_scores')
    op.drop_index(op.f('ix_product_scores_product_id'), table_name='product_scores')
    op.drop_table('product_scores')
    op.drop_index('ix_product_matches_source_target', table_name='product_matches')
    op.drop_table('product_matches')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_price_snapshots_product_time', table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_product_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('ix_orders_status_platform', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_sale_platform'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_xhs_trending_keywords_keyword'), table_name='xhs_trending_keywords')
    op.drop_table('xhs_trending_keywords')
    op.drop_index('ix_xhs_hot_topics_trending', table_name='xhs_hot_topics')
    op.drop_index(op.f('ix_xhs_hot_topics_topic_name'), table_name='xhs_hot_topics')
    op.drop_table('xhs_hot_topics')
    op.drop_table('xhs_content_templates')
    op.drop_index(op.f('ix_xhs_competitor_notes_keyword'), table_name='xhs_competitor_notes')
    op.drop_table('xhs_competitor_notes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_reply_templates_category'), table_name='reply_templates')
    op.drop_table('reply_templates')
    op.drop_index('ix_products_source_platform_source_id', table_name='products')
    op.drop_index(op.f('ix_products_source_platform'), table_name='products')
    op.drop_index(op.f('ix_products_source_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_products_category_active', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_daily_checks_check_date'), table_name='daily_checks')
    op.drop_table('daily_checks')
    op.drop_index(op.f('ix_ai_suggestions_suggestion_type'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_accounts_platform'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
